version: '3.8'

services:
  app:
    image: yt98/legora-api:latest
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      DB_USER: postgres
      PORT: 8000
      DB_USERNAME: postgres
      DB_PASSWORD: 123123
      HOST: 0.0.0.0
      DB_NAME: legora_db
      DB_DATABASE: legora_db
      DB_HOST: db
      DB_PORT: 5432
      TOKEN: RGAPI-a274348c-ada5-4d04-815b-899cc5dfb472
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: legora_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: